require:
  - rubocop-rspec
  - rubocop-performance

# Ruby (https://github.com/rubocop-hq/ruby-style-guide)
# Rails (https://github.com/rubocop-hq/rails-style-guide)
# RSpec (https://github.com/rubocop-hq/rspec-style-guide)

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - /**/*_spec.rb

Metrics/BlockLength:
  IgnoredMethods:
    - namespace
    - task
    - describe
    - context

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
